-- Run in Supabase SQL editor. Sequelize `sync({alter:true})` also creates these automatically.
create extension if not exists "uuid-ossp";
create table if not exists "Projects" (id uuid primary key default uuid_generate_v4(), title text not null, description text, status text default 'idea', tags jsonb default '[]', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists "Assets" (id uuid primary key default uuid_generate_v4(), project_id uuid references "Projects"(id) on delete cascade, kind text default 'video', file_name text, storage_path text, public_url text, size_bytes int, mime_type text, duration_sec float default 0, meta jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists "Scripts" (id uuid primary key default uuid_generate_v4(), project_id uuid references "Projects"(id) on delete cascade, title text, body text not null, tone text default 'energetic', target_platforms jsonb default '[]', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists "Hooks" (id uuid primary key default uuid_generate_v4(), script_id uuid, project_id uuid, text text not null, score float default 0, style text default 'curiosity', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists "TranscriptSegments" (id uuid primary key default uuid_generate_v4(), asset_id uuid, project_id uuid, start_sec float, end_sec float, text text, embedding_hint text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists "Clips" (id uuid primary key default uuid_generate_v4(), project_id uuid, asset_id uuid, title text, start_sec float, end_sec float, virality_score float default 0, hook_text text, captions jsonb default '[]', status text default 'suggested', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists "EditProjects" (id uuid primary key default uuid_generate_v4(), project_id uuid, clip_id uuid, edl jsonb default '{}', platform text default 'tiktok', aspect text default '9:16', version int default 1, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists "PublishJobs" (id uuid primary key default uuid_generate_v4(), project_id uuid, clip_id uuid, platform text not null, scheduled_at timestamptz, status text default 'draft', caption text, hashtags jsonb default '[]', result_url text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists "Metrics" (id uuid primary key default uuid_generate_v4(), project_id uuid, clip_id uuid, platform text, views int default 0, likes int default 0, comments int default 0, shares int default 0, retention_pct float default 0, created_at timestamptz default now(), updated_at timestamptz default now());
-- Storage bucket (or create via Dashboard > Storage):
insert into storage.buckets (id, name, public) values ('creator-assets','creator-assets', true) on conflict (id) do nothing;
