// Platform presets — single source of truth (AGENT/PUBLISHING.md §2).
// Values are defaults for short-form content; verify against each platform's
// current docs before launch. Rules live here as data, not in code.
module.exports = {
  tiktok: {
    key: 'tiktok', label: 'TikTok', aspect: '9:16',
    resolution: { w: 1080, h: 1920 },
    duration: { min: 5, target: 30, max: 60 },
    caption: { max_chars: 2200, title_max_chars: null },
    hashtags: { min: 3, max: 5, required: [] },
    caption_style: 'bold-karaoke',
    safe_zone: { top: 0.12, bottom: 0.2 },
    tone: 'casual, hook-first',
    cta_default: 'Follow for part 2',
    notes: 'Loud hook in 1s, captions burned-in, trending sound.',
  },
  reels: {
    key: 'reels', label: 'Instagram Reels', aspect: '9:16',
    resolution: { w: 1080, h: 1920 },
    duration: { min: 5, target: 30, max: 90 },
    caption: { max_chars: 2200, title_max_chars: null },
    hashtags: { min: 3, max: 5, required: [] },
    caption_style: 'clean',
    safe_zone: { top: 0.1, bottom: 0.22 },
    tone: 'visual, aspirational, concise',
    cta_default: 'Save this for later',
    notes: 'Trial reels to non-followers first.',
  },
  shorts: {
    key: 'shorts', label: 'YouTube Shorts', aspect: '9:16',
    resolution: { w: 1080, h: 1920 },
    duration: { min: 5, target: 35, max: 60 },
    caption: { max_chars: 5000, title_max_chars: 100 },
    hashtags: { min: 2, max: 3, required: ['#Shorts'] },
    caption_style: 'boxed',
    safe_zone: { top: 0.08, bottom: 0.12 },
    tone: 'searchable, keyword-rich title',
    cta_default: 'Subscribe for more',
    notes: '#Shorts in title/desc boosts shelf.',
  },
  x: {
    key: 'x', label: 'X (Twitter)', aspect: '16:9',
    resolution: { w: 1280, h: 720 },
    duration: { min: 5, target: 30, max: 140 },
    caption: { max_chars: 280, title_max_chars: null },
    hashtags: { min: 0, max: 2, required: [] },
    caption_style: 'minimal',
    safe_zone: { top: 0.05, bottom: 0.05 },
    tone: 'short, punchy, conversational',
    cta_default: 'Repost if useful',
    notes: 'Front-load punchline, subtitles essential (muted autoplay).',
  },
  linkedin: {
    key: 'linkedin', label: 'LinkedIn', aspect: '1:1',
    resolution: { w: 1080, h: 1080 },
    duration: { min: 10, target: 60, max: 600 },
    caption: { max_chars: 3000, title_max_chars: null },
    hashtags: { min: 3, max: 5, required: [] },
    caption_style: 'clean',
    safe_zone: { top: 0.05, bottom: 0.05 },
    tone: 'insightful, professional',
    cta_default: 'What is your take?',
    notes: 'Professional tone, 3-line lesson + CTA.',
  },
};
